stages:
  - build
  - test

linux-build:
    image: node
    stage: build
    before_script:
        - curl -f https://get.pnpm.io/v6.7.js | node - add --global pnpm@6
        - pnpm config set store-dir .pnpm-store
    script:
        - pnpm i
        - pnpm run r:build
    cache:
        key: "$CI_COMMIT_REF_SLUG"
        paths:
            - .pnpm-store
    artifacts:
        when: on_success
        expire_in: 1 week
        paths:
            - "apps/desktop/dist/[Mm]uzik-*"
    rules:
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
        - if: $CI_COMMIT_TAG

windows-build:
    stage: build
    before_script:
        - $ErrorActionPreference = "Stop"
        - choco upgrade nodejs --yes --no-progress
        - choco install python3 --yes --no-progress
        - (Invoke-WebRequest 'https://get.pnpm.io/v6.7.js' -UseBasicParsing).Content | node - add --global pnpm
        - pnpm config set store-dir .pnpm-store
    script:
        - pnpm i
        - pnpm run r:build
    cache:
        key: "$CI_COMMIT_REF_SLUG"
        paths:
            - .pnpm-store
    artifacts:
        when: on_success
        expire_in: 1 week
        paths:
            - "apps/desktop/dist/[Mm]uzik-*"
    tags:
        - windows
    rules:
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
        - if: $CI_COMMIT_TAG

lint:
    image: ianwalter/pnpm
    stage: test
    script:
        - pnpm i -w
        - pnpm run lint
